[Global]
hostname = <<hostname>>.afp
[Homes]
basedir regex = /home
[install]
path = /data/shares/install
volume name = Install
[data]
path = /data/shares/data
volume name = Data
[pdf]
path = /data/prints/PDF
volume name = Data
